version: 2
updates:
  - package-ecosystem: 'github-actions'
    # default location of '.github/workflows'
    directory: '/'
    open-pull-requests-limit: 10
    schedule:
      interval: 'weekly'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'docker'
    directory: 'deploy/elk/elasticsearch'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'docker'
    directory: 'deploy/elk/kibana'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'docker'
    directory: 'deploy/elk/logstash'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'docker'
    directory: 'src/ApiGateways/Mobile.Bff.Shopping/aggregator'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'docker'
    directory: 'src/ApiGateways/Web.Bff.Shopping/aggregator'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'docker'
    directory: 'src/Services/Basket/Basket.API'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'docker'
    directory: 'src/Services/Catalog/Catalog.API'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'docker'
    directory: 'src/Services/Identity/Identity.API'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'docker'
    directory: 'src/Services/Ordering/Ordering.API'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'docker'
    directory: 'src/Services/Ordering/Ordering.BackgroundTasks'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'docker'
    directory: 'src/Services/Ordering/Ordering.SignalrHub'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'docker'
    directory: 'src/Services/Payment/Payment.API'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'docker'
    directory: 'src/Services/Webhooks/Webhooks.API'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'docker'
    directory: 'src/Web/WebhookClient'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'docker'
    directory: 'src/Web/WebMVC'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'docker'
    directory: 'src/Web/WebSPA'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'docker'
    directory: 'src/Web/WebStatus'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'npm'
    directory: 'src/Web/WebSPA/Client'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/ApiGateways/Mobile.Bff.Shopping/aggregator'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/ApiGateways/Web.Bff.Shopping/aggregator'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/BuildingBlocks/Devspaces.Support'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/BuildingBlocks/EventBus/EventBus'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/BuildingBlocks/EventBus/EventBus.Tests'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/BuildingBlocks/EventBus/EventBusRabbitMQ'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/BuildingBlocks/EventBus/EventBusServiceBus'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/BuildingBlocks/EventBus/IntegrationEventLogEF'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/BuildingBlocks/WebHostCustomization/WebHost.Customization'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/Services/Basket/Basket.API'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/Services/Basket/Basket.FunctionalTests'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/Services/Basket/Basket.UnitTests'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/Services/Catalog/Catalog.API'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/Services/Catalog/Catalog.FunctionalTests'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/Services/Catalog/Catalog.UnitTests'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/Services/Identity/Identity.API'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/Services/Ordering/Ordering.API'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/Services/Ordering/Ordering.BackgroundTasks'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/Services/Ordering/Ordering.Domain'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/Services/Ordering/Ordering.FunctionalTests'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/Services/Ordering/Ordering.Infrastructure'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/Services/Ordering/Ordering.SignalrHub'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/Services/Ordering/Ordering.UnitTests'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/Services/Payment/Payment.API'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/Services/Webhooks/Webhooks.API'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/Tests/Services/Application.FunctionalTests'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/Web/WebhookClient'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/Web/WebMVC'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/Web/WebSPA'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/Web/WebStatus'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

# Built with ‚ù§ by [Pipeline Foundation](https://pipeline.foundation)
